name: Build Hermes

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw32
        update: true
        install: >-
          git
          mingw-w64-i686-toolchain
          mingw-w64-i686-python
          mingw-w64-i686-python-pygments
          mingw-w64-i686-python-yaml
          mingw-w64-i686-icu
          mingw-w64-i686-ninja
          mingw-w64-i686-readline
          mingw-w64-i686-dlfcn

    - name: Checkout local repo
      uses: actions/checkout@v4
      with:
        repository: zxunge/Hermes

    - name: Checkout Hermes
      uses: actions/checkout@v4
      with:
        repository: facebook/hermes
        path: hermes
 
    - name: Build Hermes
      shell: msys2 {0}
      run: |
        # Remove system Python
        rm -rf /c/hostedtoolcache/windows/Python
        
        wget -q https://github.com/zxunge/mingw-package-archives/raw/refs/heads/main/mingw-w64-i686-libbacktrace-r53.1da441c-3-any.pkg.tar.zst
        wget -q https://repo.msys2.org/mingw/mingw32/mingw-w64-i686-cmake-3.31.6-1-any.pkg.tar.zst
        pacman -U --noconfirm mingw-w64-i686-libbacktrace-r53.1da441c-3-any.pkg.tar.zst
        pacman -U --noconfirm mingw-w64-i686-cmake-3.31.6-1-any.pkg.tar.zst

        # Patch build
        pushd hermes/ 
        git apply ../0001-Fix-llvh-build-with-problematic-includes.patch
        git apply ../0001-Fix-win32-macro.patch
        git apply ../0001-Fix-atomic.patch
        # git apply ../0001-Fix-math.h-usage.patch
        git apply ../0001-Fix-rand_s.patch
        cp ../Atomic.cpp external/llvh/lib/Support/
        popd

        cmake -S hermes -B build -G Ninja
        cmake --build ./build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Hermes
        path: build
