name: Build Hermes

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw32
        update: true
        install: >-
          mingw-w64-i686-toolchain
          mingw-w64-i686-cmake
          mingw-w64-i686-python
          mingw-w64-i686-python-pip
          mingw-w64-i686-python-pygments
          mingw-w64-i686-python-yaml
          mingw-w64-i686-python-virtualenv
          mingw-w64-i686-ninja

    - name: Build Hermes
      shell: msys2 {0}
      run: |
        # Create Python virtualenv
        virtualenv -p python3 hermes_venv
        source hermes_venv/bin/activate
        cd hermes_venv
        pip install pygments
        pip install yaml-1.3

        git clone https://github.com/facebook/hermes.git
        cmake -S hermes -B build -G Ninja
        cmake --build ./build

        deactivate

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Hermes
        path: hermes_venv/hermes/build
