name: Build Hermes

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw32
        update: true
        install: >-
          mingw-w64-i686-toolchain
          mingw-w64-i686-cmake
          mingw-w64-i686-ninja

    - name: Checkout Hermes
      uses: actions/checkout@v4
      with:
        repository: facebook/hermes

    - name: Build Hermes
      shell: msys2 {0}
      run: |
        cmake -S hermes -B build -G Ninja
        cmake --build ./build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Hermes
        path: build
