name: Build Hermes

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw32
        update: true
        install: >-
          mingw-w64-i686-toolchain
          mingw-w64-i686-cmake
          mingw-w64-i686-python
          mingw-w64-i686-python-pip
          mingw-w64-i686-python-pygments
          mingw-w64-i686-python-yaml
          mingw-w64-i686-icu
          mingw-w64-i686-python-virtualenv
          mingw-w64-i686-ninja

    - name: Checkout Hermes
      uses: actions/checkout@v4
      with:
        repository: facebook/hermes
        path: hermes_venv/hermes
 
    - name: Build Hermes
      shell: msys2 {0}
      run: |
        wget -q https://github.com/zxunge/mingw-package-archives/blob/main/mingw-w64-i686-libbacktrace-r53.1da441c-3-any.pkg.tar.zst
        pacman -U --no-confirm mingw-w64-i686-libbacktrace-r53.1da441c-3-any.pkg.tar.zst
        
        # Create Python virtualenv
        virtualenv -p python3 hermes_venv
        source hermes_venv/bin/activate
        cd hermes_venv
        pip install pygments
        pip install pyyaml

        cmake -S hermes -B build -G Ninja
        cmake --build ./build

        deactivate

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Hermes
        path: hermes_venv/hermes/build
